version: "3"
services:
  nzbtoproxy:
    build: ./docker/.
    ports:
      - "1080:1080"
      - "1443:1443"
    volumes:
      - .:/var/www
    networks:
      - nzbproxy

  torproxy:
    image: peterdavehello/tor-socks-proxy
    ports:
      - "9150:9150"
    networks:
      - nzbproxy
    depends_on:
      - nzbtoproxy

networks:
  nzbproxy:
    driver: bridge
